### PR TITLE
Add support for RTL

### PR DESCRIPTION
**Pull request by evanwang0**
This PR adds support for RTL and addresses issue #88. Feel free to request changes, overwrite, or ignore and close this PR. The PR is provided as a courtesy. 

Here is a summary of the changes:
- Adds `rtl` flag to `init` function
- Adds enum `WritingDirection`
- Adds properties `right` & `bottom` to `FocusableComponentLayout`
- Refactors `getChildClosestToOrigin` to support search from the top right corner of the viewport based on writing direction
- Refactors code depending on `isIncrementalDirection` to support RTL
- Refactors code to use `right`/`bottom`
- Adds support for `rtl` in the `VisualDebugger`

Notes:
- I've removed the `no-nested-ternary` eslint rule as it's useful for concisely defining cases. 
- The main logical change in this PR is to `getChildClosestToOrigin`. All of the other changes should preserve logic in either writing direction. The changes to the other functions are primarily to preserve the meaning of the variable `isIncrementalDirection`. In other words, the booleans `isVertical` and `isIncrementalDirection` together map to `left`, `up`, `right`, `down`. However, with RTL support, `isVertical`, `isIncrementalDirection`, and `writingDirection` is needed to map to the same directions. These functions could be rewritten to use the direction directly so that logic is identical regardless of writing direction.

### CODE REVIEW

**Comment by akash-kush9** [comment]
> Worth mentioning that the issue requests RTL on the fly and while not implemented in the PR can be done through replacing `this.writingDirection` with a form of `document.dir`

Hi @evanwang0, Quick question regarding this PR, Once integrated will this allow left arrow press move the focus from right to left ( same direction ) or left to right ( inverted direction )?

**Comment by evanwang0** [comment]
@akash-kush9 That is correct.

**Comment by jeev1989** [comment]
Thanks @evanwang0 👍  Tried out this fix and it seems to be working as expected.
@asgvard , @predikament : When can we expect this fix to be reviewed/merged and made available?

**Comment by predikament** [comment]
> Thanks @evanwang0 👍 Tried out this fix and it seems to be working as expected. @asgvard , @predikament : When can we expect this fix to be reviewed/merged and made available?

We've just added this task to our backlog and it will be reviewed ASAP; We'd like to get this functionality included in a good way.

**Review by Braggiouy — APPROVED** [review]

**Review by predikament — APPROVED** [review]
Looks fine to me as well.

@asgvard, @xavi160: Any opinions? ☺️

**Comment by sarah-harissa** [comment]
I am waiting for the approval, thank you guys.

**Review by asgvard — APPROVED** [review]

**Pull request merged**
