### PR TITLE
Update setKeyCode API to allow mapping direction to multiple keyCodes

### PR DESCRIPTION
**Pull request by joshreep**
As mentioned in [this issue](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/issues/28), I would like to add support for multiple keyCode mapping.  This will be necessary for users who plan to use a gamepad with a joystick and a d-pad.

### CODE REVIEW

**Comment by predikament** [comment]
@joshreep: This looks interesting! We will review it as soon as we can.

Cheers for the contribution - We appreciate small changes like this that can help expand the usage to other platforms (while still having the code remain _relatively_ straightforward).

**Comment by joshreep** [comment]
> @joshreep: This looks interesting! We will review it as soon as we can.
> 
> Cheers for the contribution - We appreciate small changes like this that can help expand the usage to other input devices (while still having the code remain _relatively_ straightforward).

Thanks, @predikament!  I truly like what you guys have done.  It seems simpler and lighter weight than a lot of the other libs that do similar stuff.  At the moment, we've forked your repo and are symlinking to the updated branch, but obviously, we'd love to just install directly from npm and not have to maintain the code ourselves, haha.  Can't wait to hear the feedback when you get a moment.  🙂

**Review by asgvard — APPROVED** [review]
Looks good! 👍 Thank you for the contribution :)

**Comment by asgvard** [comment]
Will make a new release soon.

**Pull request merged**
