### PR TITLE
Handle `StrictMode` without custom `useEffectOnce` hook

### PR DESCRIPTION
**Pull request by zemlanin**
Custom `useEffectOnce` hook doesn't always run effect's cleanup function — for example, if the app navigates away from the screen as soon as that that screen is rendered (either automatically or if user presses Back button before slow TV has ran all effects), see https://github.com/NoriginMedia/Norigin-Spatial-Navigation/issues/25#issuecomment-1330935122 for some details

Instead of complicating `useEffectOnce`, in this PR I've tried to remove the need in it and fix the issue #8 it tried to fix the other way

### CODE REVIEW

**Comment by zemlanin** [comment]
Argh…

As it is, even thought a single element is focused in `StrictMode`, every element still becomes focused because of `autoRestoreFocus`, firing `onFocus` callbacks (like "scroll into view")

**Comment by asgvard** [comment]
Hello @zemlanin , 
Seems like we've got more of the similar issues in our internal projects related to this problem with the new `useEffectOnce` hook.
I am currently looking into removing it, because it seems like a hack anyway. Theoretically the library shouldn't care if the component is added or re-mounted multiple times, it should be handled properly, so I will find a root cause for this and try to make it work in all scenarios.
You're right that `autoRestore` focus is causing a lot of unnecessary auto-focus events when the items are removed and then immediately re-added. I will look into making it a denounced function instead so if there are many items removed/added in one go (rendering cycle), it will only try to restore focus on the latest relevant item. This `autoRestoreFocus` never meant to be a 100% reliable feature, it was more of an attempt to ensure the focus is never lost when the item just gets conditionally unmounted. I will keep you posted on this PR.

**Comment by asgvard** [comment]
I will probably also revert this PR: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/pull/54/files
Because even though it practically makes sense in that scenario, it should not be needed to update children if the parent is getting removed. If the parent gets unmounted, children are unmounted first, and they should call the cleanup function first. I think the root cause is that custom effect again.

**Comment by zemlanin** [comment]
Thanks. And sorry for keeping the PR in drafts with no progress/changes — juggling a lot of stuff for the last few months

**Comment by asgvard** [comment]
No worries, sorry for not looking into this issue for a long time as well :)
I'll close this one in favor of #79 . I hope it will resolve all the related issues and will make the behavior more clean without the `useEffectOnce` hook.

**Pull request closed without merging**
