### PR TITLE
Fixes #36 - Babel and CoreJS used instead of ts-loader to transpile and polyfill

### LINKED ISSUE #36: Built index.js has ES6 functionalites (Reflect) - Build not es5 compliant
**Describe the bug**
1.1.1 Built version of Norigin Spatial Navigation is not es5 compliant

**To Reproduce**
Include it in a project and make it run on Chrome<49 / Browser without Reflect API support (it's from ES6)

**Expected behavior**
A built version without Reflect

**Screenshots**
Not required

@adrian-wozniak - @asgvard

### PR DESCRIPTION
**Pull request by MFlyer**
@predikament & @asgvard do you want to check this?
Main change is moving from ts-loader to Babel+CoreJS that provides a clean and polyfilled ES5 build, this closes #36

### CODE REVIEW

**Comment by siarheipashkevich** [comment]
Any news about this PR ?

**Comment by predikament** [comment]
> @predikament & @asgvard do you want to check this? Main change is moving from ts-loader to Babel+CoreJS that provides a clean and polyfilled ES5 build, this closes #36

Hello @MFlyer! 

Thanks a lot for your contribution, it is highly appreciated.

I wanted to inform you that we have scheduled this (_technically_ #36) to be looked into during our current sprint, so it should be addressed soon.

(@siarheipashkevich: I hope this answers your question as well. ⬆️)

As a side note we are not 100% convinced regarding replacing the loader to resolve this issue, so we will look a bit more into the pros and cons of the different approaches in relation to fixing this. 

If we do decide this change is the way to go then we will likely merge this PR as it stands, but we'll of course let you know regardless.

Cheers,
@predikament

**Comment by asgvard** [comment]
Hello,

Since declaration files are quite crucial, we would like to still rely on the TS config and ts-loader. We are also using ts-loader on other projects, so we'd prefer to have it consistent.
However, this problem can be solved by replacing `Reflect` with the other alternative.
Also what we've done on some projects that require ES5, we have added this package to a Bable loader on that project itself via `include` path, so it gets transpiled additionally in the host project. That could be a temporary solution for anyone having this problem. It's not a lot of work in terms of finding a solution to it and make a new release, but it needs to be agreed internally on who will work on it and when, and that takes time :)

Thanks for your patience.

**Comment by MFlyer** [comment]
@asgvard any news on this?
Cheers
M.

**Comment by guilleccc** [comment]
Hi @MFlyer ,

We decided to replace `Reflect.deleteProperty` by just using `delete`, as it was done in this [PR](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/pull/51). Then we haven't introduce any change to ts-loader.
Please let me know if that works properly for you.

In the meantime I will close this PR.

**Pull request closed without merging**
